### ISSUE TITLE
Temperature write values not correct due readTransform without writeTransformation

### ISSUE THREAD

**Issue by ggaljoen** [sirjackal/brink-modbus#1]
Small adjustment to be made to the temperature values divide by 10 for decimal display.
writeTransformation should by applied, register is expecting value multiplied by 10.
Register 6101 6102 6103 6110 6111: Value is in tenth of degrees Celsius

Thing data holding6101 @ "Rekuperace" [ readStart="6101", readValueType="uint16", readTransform="JS(divide10.js)", writeStart="6101", writeValueType="int16", writeType="holding", writeTransform="JS(multiply10.js)" ] 

Thank you for this nice integration!

**Comment by sirjackal** [comment]
Hello, thanks for your update! I don't use registers 6110 and 6111 right now. What is actually "Frost control temperature" and "Frost control minimum inlet temperature"?

**Comment by ggaljoen** [comment]
The unit has an internal heater element of 1000 watt, to prevent the heat exchanger from getting clogged by frozen air/humidity. These registers do interfere with the unit logic for activating this heater:
4060 Status preheater
4061 Capacity of preheater Range: 0 - 100 The capacity is a percentage of the maximum capacity.

Found the issue while adjust the settings  for an external post-heater 6131.

**Comment by sirjackal** [comment]
According to the documentation, frost control temperature could be set from 0.0 to 3.0 °C and frost control minimum inlet temperature could be set from 7.0 to 22 °C. I don't get what are these settings for.

I could imagine setting the temperature interval when the preheater should be turned on, but that should include negative temperatures too. So maybe if this is what "Frost control temperature" is for, it's not 0.0 to 3.0 °C but -273,15 to 3.0 °C and for the negative temperatures the preheater is turned on automatically.

The second value I could imagine to be set is the temperature of the air coming from the preheater further to the unit. So maybe that's the "Frost control minimum inlet temperature"?

Have you done some more research or experiments?

**Comment by sirjackal** [comment]
Issue with setting bypass temperatures was fixed in this [commit](https://github.com/sirjackal/brink-modbus/commit/7fee0e17545dbd918d0126654ba3ea32e6e7d65e).

**Comment by ggaljoen** [comment]
That was a quick fix/commit! Thank you!

Did you check frost prevent settings on your unit display?
Mine got different min/max and step for 6110.

Frost control temperature 6110: on my unit on the display 6110 has a range from -1.5 to +1.5 with a step of 0.1 and not 0.0 to 3.0 (0.5) like all manuals mention
Frost control minimum inlet temperature 6111: is the minimum air temperature blown into the house

I guess both triggers are required before the heater kicks in.
So far I did not got any higher value other then 0 on 4061 Capacity of preheater %.
At the moment the intake is as low as 3,9°C, fingers crossed....
Got my settings tweaked today; if intake air gets cooler then +1,5°C , one of the next nights, I hope to see the result.
Will update here the result, if any.

**Comment by ggaljoen** [comment]
No reading but 0 on 4061, maybe because no pre-heather...
For my post-heather 6130 and 6131 are working.
